openapi: 3.1.0
info:
  title: Faktúry Analytics API
  description: |
    API pre zobrazovanie a analýzu faktúr v Google Sheets.
    
    **Funkcie:**
    - Zobrazovanie zoznamu faktúr
    - Zobrazovanie detailov faktúry
    - Vyhľadávanie faktúr
    - Základné štatistiky
    - Rozšírená analytika (obrat firiem, platobná disciplína, obchodníci, trendy)
    
  version: 2.0.0

servers:
  - url: https://adsun-sprava-faktur-production.up.railway.app
    description: Production Server

paths:
  /health:
    get:
      operationId: checkHealth
      summary: Kontrola stavu API
      description: Zistí, či API beží a je dostupné
      responses:
        '200':
          description: API beží správne
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK
                  message:
                    type: string

  /api/faktury:
    get:
      operationId: getAllFaktury
      summary: Získa zoznam všetkých faktúr
      description: Vráti všetky faktúry zo Google Sheets
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Zoznam faktúr
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Faktura'
                  count:
                    type: integer
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/faktury/{cislo}:
    get:
      operationId: getFakturaById
      summary: Získa detail faktúry
      description: Vráti kompletné informácie o faktúre podľa čísla
      security:
        - ApiKeyAuth: []
      parameters:
        - name: cislo
          in: path
          required: true
          description: Číslo faktúry (napr. 2025001)
          schema:
            type: string
          example: "2025001"
      responses:
        '200':
          description: Detail faktúry
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    $ref: '#/components/schemas/Faktura'
        '404':
          description: Faktúra nenájdená
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/faktury/search:
    get:
      operationId: searchFaktury
      summary: Vyhľadá faktúry podľa kritérií
      description: Filtruje faktúry podľa partnera, dátumu a stavu úhrady
      security:
        - ApiKeyAuth: []
      parameters:
        - name: partner
          in: query
          description: Názov partnera (hľadá v reťazci, case-insensitive)
          schema:
            type: string
          example: "ADSUN"
        - name: datum_od
          in: query
          description: Dátum vystavenia od (YYYY-MM-DD)
          schema:
            type: string
            format: date
        - name: datum_do
          in: query
          description: Dátum vystavenia do (YYYY-MM-DD)
          schema:
            type: string
            format: date
        - name: zaplatene
          in: query
          description: Filtruje zaplatené (true) alebo nezaplatené (false) faktúry
          schema:
            type: string
            enum: ["true", "false"]
      responses:
        '200':
          description: Výsledky vyhľadávania
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Faktura'
                  count:
                    type: integer
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/statistiky:
    get:
      operationId: getStatistiky
      summary: Získa základné štatistiky faktúr
      description: Vráti celkový počet faktúr, sumy, zaplatené a nezaplatené
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Štatistiky
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: object
                    properties:
                      celkovy_pocet:
                        type: integer
                      celkova_suma:
                        type: number
                      nezaplatene_pocet:
                        type: integer
                      nezaplatene_suma:
                        type: number
                      zaplatene_pocet:
                        type: integer
                      zaplatene_suma:
                        type: number
                      mena:
                        type: string
                        example: EUR
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/analytics/firmy:
    get:
      operationId: getAnalyticsFirmy
      summary: Obrat podľa partnerov/firiem
      description: Vráti zoznam všetkých partnerov s celkovým obratom, počtom faktúr a priemernými hodnotami
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Obrat podľa firiem
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        partner:
                          type: string
                        ico:
                          type: string
                        pocet_faktur:
                          type: integer
                        celkovy_obrat:
                          type: number
                        zaplatene_suma:
                          type: number
                        nezaplatene_suma:
                          type: number
                        priemernaFaktura:
                          type: number
                  count:
                    type: integer
                  mena:
                    type: string
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/analytics/splatnost:
    get:
      operationId: getAnalyticsSplatnost
      summary: Analýza dodržiavania termínov splácania
      description: Vráti štatistiky o platobnej disciplíne - faktúry zaplatené včas vs neskoro, priemerné meškanie
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Analýza platobnej disciplíny
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: object
                    properties:
                      zaplatene_celkom:
                        type: integer
                      zaplatene_v_cas:
                        type: integer
                      zaplatene_neskoro:
                        type: integer
                      percento_v_cas:
                        type: integer
                      priemerne_meskanie_dni:
                        type: integer
                      nezaplatene_po_termine:
                        type: integer
                      nezaplatene_po_termine_suma:
                        type: number
                      mena:
                        type: string
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/analytics/obchodnici:
    get:
      operationId: getAnalyticsObchodnici
      summary: Štatistiky podľa obchodníkov
      description: Vráti výkonnosť jednotlivých obchodníkov (kto vystavoval faktúry)
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Štatistiky obchodníkov
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        vystavil:
                          type: string
                        pocet_faktur:
                          type: integer
                        celkova_suma:
                          type: number
                        zaplatene_pocet:
                          type: integer
                        zaplatene_suma:
                          type: number
                        nezaplatene_pocet:
                          type: integer
                        nezaplatene_suma:
                          type: number
                        pocet_klientov:
                          type: integer
                        priemerna_faktura:
                          type: number
                  count:
                    type: integer
                  mena:
                    type: string
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/analytics/mesacne:
    get:
      operationId: getAnalyticsMesacne
      summary: Mesačné štatistiky (trendová analýza)
      description: Vráti obrat a počet faktúr po mesiacoch
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Mesačné štatistiky
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        mesiac:
                          type: string
                          example: "2025-10"
                        pocet_faktur:
                          type: integer
                        celkova_suma:
                          type: number
                        zaplatene_pocet:
                          type: integer
                        zaplatene_suma:
                          type: number
                        nezaplatene_pocet:
                          type: integer
                        nezaplatene_suma:
                          type: number
                        priemerna_faktura:
                          type: number
                  count:
                    type: integer
                  mena:
                    type: string
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/analytics/top-klienti:
    get:
      operationId: getAnalyticsTopKlienti
      summary: Top klientov podľa obratu
      description: Vráti rebríček najvýznamnejších klientov podľa celkového obratu
      security:
        - ApiKeyAuth: []
      parameters:
        - name: limit
          in: query
          description: Počet top klientov (default 10)
          schema:
            type: integer
            default: 10
          example: 10
      responses:
        '200':
          description: Top klienti
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        partner:
                          type: string
                        ico:
                          type: string
                        celkovy_obrat:
                          type: number
                        pocet_faktur:
                          type: integer
                        priemerna_faktura:
                          type: number
                  count:
                    type: integer
                  mena:
                    type: string
        '401':
          $ref: '#/components/responses/Unauthorized'

components:
  schemas:
    Faktura:
      type: object
      properties:
        cislo:
          type: string
          example: "2025001"
        typ:
          type: string
          example: "Faktúra - vydaná"
        datum_vystavenia:
          type: string
        datum_splatnosti:
          type: string
        partner:
          type: string
        ico:
          type: string
        celkom_s_dph:
          type: number
        celkom_bez_dph:
          type: number
        zostava_uhradit:
          type: number
        datum_uhrady:
          type: string
        vystavil:
          type: string
        mena:
          type: string
          example: "EUR"

    Error:
      type: object
      properties:
        status:
          type: string
          example: ERROR
        message:
          type: string

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Faktury-API-Key
      description: API kľúč pre autentifikáciu

  responses:
    Unauthorized:
      description: Neautorizovaný prístup
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
